version: 2
jobs:
  # Define in CircleCi Project Variables: $DOCKERHUB_REPO, $DOCKERHUB_USER, $DOCKERHUB_PASS
  # Publish jobs require those variables
  amd64:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            sudo docker build --pull -t "$DOCKERHUB_REPO:$CIRCLE_TAG-amd64" -f Dockerfile .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push "$DOCKERHUB_REPO:$CIRCLE_TAG-amd64"
  arm32v7:
    machine:
      enabled: true
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            #
            sudo docker build --pull -t "$DOCKERHUB_REPO:$CIRCLE_TAG-arm32v7" -f Dockerfile.arm32v7 .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push "$DOCKERHUB_REPO:$CIRCLE_TAG-arm32v7"
  arm64v8:
    machine:
      enabled: true
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            #
            sudo docker build --pull -t "$DOCKERHUB_REPO:$CIRCLE_TAG-arm64v8" -f Dockerfile.arm64v8 .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push "$DOCKERHUB_REPO:$CIRCLE_TAG-arm64v8"
  multiarch:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - run:
          command: |
            # Turn on Experimental features
            sudo mkdir $HOME/.docker
            sudo sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
            #
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            #
            sudo docker manifest create --amend "$DOCKERHUB_REPO:$CIRCLE_TAG" "$DOCKERHUB_REPO:$CIRCLE_TAG-amd64" "$DOCKERHUB_REPO:$CIRCLE_TAG-arm32v7" "$DOCKERHUB_REPO:$CIRCLE_TAG-arm64v8"
            sudo docker manifest annotate "$DOCKERHUB_REPO:$CIRCLE_TAG" "$DOCKERHUB_REPO:$CIRCLE_TAG-amd64" --os linux --arch amd64
            sudo docker manifest annotate "$DOCKERHUB_REPO:$CIRCLE_TAG" "$DOCKERHUB_REPO:$CIRCLE_TAG-arm32v7" --os linux --arch arm --variant v7
            sudo docker manifest annotate "$DOCKERHUB_REPO:$CIRCLE_TAG" "$DOCKERHUB_REPO:$CIRCLE_TAG-arm64v8" --os linux --arch arm64 --variant v8
            sudo docker manifest push "$DOCKERHUB_REPO:$CIRCLE_TAG" -p

workflows:
  version: 2
  publish:
    jobs:
      - amd64:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
      - arm32v7:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
      - arm64v8:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
      - multiarch:
          requires:
            - amd64
            - arm32v7
            - arm64v8
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
